# Generated by Django 4.2.3 on 2023-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_upload_upload_file_alter_upload_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(default='tile', max_length=20),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Upload_File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Upload_Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
