# Generated by Django 4.2.3 on 2023-09-23 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_upload_title_alter_upload_upload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Upload_File',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Upload_Image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
